/// Build Engine — a modular, data-driven game engine core.
///
/// The core provides generic verbs (entities, components, events, plugins);
/// game-specific content belongs in plugins, not here.
library;

export 'src/character/character_component.dart';
export 'src/character/character_events.dart';
export 'src/character/character_service.dart';
export 'src/component/component_store.dart';
export 'src/components/health_component.dart';
export 'src/components/progression_component.dart';
export 'src/components/resource_component.dart';
export 'src/components/stat_component.dart';
export 'src/components/status_component.dart';
export 'src/components/tag_set.dart';
export 'src/content/built_in_content_factories.dart';
export 'src/content/content_definition.dart';
export 'src/content/content_errors.dart';
export 'src/content/content_registry.dart';
export 'src/content/json_helpers.dart';
export 'src/entity/entity_id.dart';
export 'src/entity/entity_registry.dart';
export 'src/event/event_bus.dart';
export 'src/modifier/modifier.dart';
export 'src/modifier/modifier_collection.dart';
export 'src/modifier/modifier_resolver.dart';
export 'src/modifier/modifier_source.dart';
export 'src/plugin/game_plugin.dart';
export 'src/plugin/plugin_context.dart';
export 'src/plugin/plugin_exceptions.dart';
export 'src/plugin/plugin_manager.dart';
export 'src/plugin/plugin_sdk.dart';
export 'src/progression/progression_definition.dart';
export 'src/progression/progression_engine.dart';
export 'src/progression/progression_events.dart';
export 'src/progression/progression_state.dart';
export 'src/query/queries.dart';
export 'src/query/query.dart';
export 'src/query/query_engine.dart';
export 'src/resource/resource_definition.dart';
export 'src/resource/resource_events.dart';
export 'src/resource/resource_exceptions.dart';
export 'src/resource/resource_pool.dart';
export 'src/resource/resource_state.dart';
export 'src/rng/rng_service.dart';
export 'src/rule/condition.dart';
export 'src/rule/effect.dart';
export 'src/rule/effect_events.dart';
export 'src/rule/event_counter.dart';
export 'src/rule/rule.dart';
export 'src/rule/rule_context.dart';
export 'src/rule/rule_engine.dart';
export 'src/spatial/container.dart';
export 'src/spatial/placement_exception.dart';
export 'src/spatial/placement_rule.dart';
export 'src/spatial/position.dart';
export 'src/spatial/slot.dart';
export 'src/spatial/spatial_relation.dart';
